Repository codestates-seb/seb40_main_020, pull requests merged in 2022-11, with the labels that each got.

#32 📦 chore : react-hook-form 설치
  OneCoin/Client/package-lock.json
  OneCoin/Client/package.json
  OneCoin/Client/public/index.html
  OneCoin/Client/src/App.tsx
  OneCoin/Client/src/pages/FindPassword/FindPassword.tsx
  OneCoin/Client/src/pages/FindPassword/ResetPassword.tsx
  OneCoin/Client/src/pages/FindPassword/style.ts
  OneCoin/Client/src/pages/Login/Login.tsx
  OneCoin/Client/src/pages/Login/style.ts
  OneCoin/Client/src/pages/SignUp/SignUp.tsx
  OneCoin/Client/src/pages/SignUp/style.ts
Labels: ⛲ Type: Feature/Function, 🚃Priority: Low

#47 ✨feat : 거래소 페이지 제작
  OneCoin/Client/src/App.tsx
  OneCoin/Client/src/components/Aside/index.tsx
  OneCoin/Client/src/components/Aside/style.ts
  OneCoin/Client/src/components/Button/index.tsx
  OneCoin/Client/src/components/Button/style.ts
  OneCoin/Client/src/components/Tab/index.tsx
  OneCoin/Client/src/components/Tab/style.ts
  OneCoin/Client/src/pages/Exchange/components/Chart/index.tsx
  OneCoin/Client/src/pages/Exchange/components/Chart/style.ts
  OneCoin/Client/src/pages/Exchange/components/Hold/index.tsx
  OneCoin/Client/src/pages/Exchange/components/Hold/style.ts
  OneCoin/Client/src/pages/Exchange/components/Order/index.tsx
  OneCoin/Client/src/pages/Exchange/components/Order/style.ts
  OneCoin/Client/src/pages/Exchange/components/Quote/index.tsx
  OneCoin/Client/src/pages/Exchange/components/Quote/style.ts
  OneCoin/Client/src/pages/Exchange/components/QuoteList/index.tsx
  OneCoin/Client/src/pages/Exchange/components/QuoteList/style.ts
  OneCoin/Client/src/pages/Exchange/index.tsx
  OneCoin/Client/src/pages/Exchange/style.ts
  OneCoin/Client/src/pages/index.tsx
  OneCoin/Client/src/store/index.ts
  OneCoin/Client/src/store/index.tsx
  OneCoin/Client/src/styles/globalStyle.ts
  OneCoin/Client/src/utills/calculate.ts
  OneCoin/Client/src/utills/types/index.ts
  OneCoin/Client/src/utills/types/index.tsx
Labels: ⛲ Type: Feature/Function

#48 ✨feat : 투자내역 페이지 생성
  OneCoin/Client/package-lock.json
  OneCoin/Client/package.json
  OneCoin/Client/src/App.tsx
  OneCoin/Client/src/components/Layout/index.tsx
  OneCoin/Client/src/components/Layout/style.ts
  OneCoin/Client/src/components/Table/index.tsx
  OneCoin/Client/src/components/Table/style.ts
  OneCoin/Client/src/pages/Balance/components/Pagination/index.tsx
  OneCoin/Client/src/pages/Balance/components/Pagination/style.ts
  OneCoin/Client/src/pages/Balance/components/TableInfo/index.tsx
  OneCoin/Client/src/pages/Balance/components/TableInfo/style.ts
  OneCoin/Client/src/pages/Balance/components/TabsLink/index.tsx
  OneCoin/Client/src/pages/Balance/components/TabsLink/style.ts
  OneCoin/Client/src/pages/Balance/index.tsx
  OneCoin/Client/src/pages/Balance/style.ts
  OneCoin/Client/src/styles/globalStyle.ts
  OneCoin/Client/src/utills/constants/investments.ts
Labels: ⛲ Type: Feature/Function

#54 ✨feat : 공용 - Footer, Header 컴포넌트 제작
  OneCoin/Client/@types/global/index.d.ts
  OneCoin/Client/src/assets/images/index.tsx
  OneCoin/Client/src/assets/images/one.png
  OneCoin/Client/src/components/Footer/index.tsx
  OneCoin/Client/src/components/Footer/syle.ts
  OneCoin/Client/src/components/Header/index.tsx
  OneCoin/Client/src/components/Header/style.ts
  OneCoin/Client/src/utills/constants/investments.ts
Labels: ⛲ Type: Feature/Function

#61 ✨feat : 보유자산페이지 퍼블 작업 외
  OneCoin/Client/src/App.tsx
  OneCoin/Client/src/components/Aside/CoinList/index.tsx
  OneCoin/Client/src/components/Aside/CoinList/style.ts
  OneCoin/Client/src/components/Aside/index.tsx
  OneCoin/Client/src/components/Aside/style.ts
  OneCoin/Client/src/components/Layout/index.tsx
  OneCoin/Client/src/components/Layout/style.ts
  OneCoin/Client/src/components/Tab/style.ts
  OneCoin/Client/src/components/Table/index.tsx
  OneCoin/Client/src/components/Table/style.ts
  OneCoin/Client/src/pages/Balance/components/TableInfo/style.ts
  OneCoin/Client/src/pages/Balance/style.ts
  OneCoin/Client/src/pages/Balances/components/ChargingTab/index.tsx
  OneCoin/Client/src/pages/Balances/components/ChargingTab/style.ts
  OneCoin/Client/src/pages/Balances/components/DepositDetailTab/index.tsx
  OneCoin/Client/src/pages/Balances/components/DepositDetailTab/style.ts
  OneCoin/Client/src/pages/Balances/components/DepositTab/index.tsx
  OneCoin/Client/src/pages/Balances/components/DepositTab/style.ts
  OneCoin/Client/src/pages/Balances/components/TotalAsset/index.tsx
  OneCoin/Client/src/pages/Balances/components/TotalAsset/style.ts
  OneCoin/Client/src/pages/Balances/index.tsx
  OneCoin/Client/src/pages/Balances/style.ts
  OneCoin/Client/src/pages/Exchange/index.tsx
  OneCoin/Client/src/pages/History/components/ButtonList/index.tsx
  OneCoin/Client/src/pages/History/components/ButtonList/style.ts
  OneCoin/Client/src/pages/History/components/HistoryHeader/index.tsx
  OneCoin/Client/src/pages/History/components/HistoryHeader/style.ts
  OneCoin/Client/src/pages/History/index.tsx
  OneCoin/Client/src/pages/History/style.ts
  OneCoin/Client/src/pages/WaitOrders/index.tsx
  OneCoin/Client/src/pages/WaitOrders/style.ts
  OneCoin/Client/src/styles/index.tsx
  OneCoin/Client/src/utills/constants/balances.ts
  OneCoin/Client/src/utills/constants/investments.ts
Labels: ⛲ Type: Feature/Function

#65 ✨feat : 회원가입 api 수정중
  OneCoin/Client/src/App.tsx
  OneCoin/Client/src/components/Aside/Rank.tsx
  OneCoin/Client/src/components/Aside/index.tsx
  OneCoin/Client/src/components/Layout/style.ts
  OneCoin/Client/src/pages/FindPassword/index.tsx
  OneCoin/Client/src/pages/Login/index.tsx
  OneCoin/Client/src/pages/ResetPassword/index.tsx
  OneCoin/Client/src/pages/ResetPassword/style.ts
  OneCoin/Client/src/pages/SignUp/index.tsx
  OneCoin/Client/src/pages/Swap/index.tsx
  OneCoin/Client/src/pages/Swap/style.ts
  OneCoin/Client/src/pages/SwapResult/index.tsx
  OneCoin/Client/src/pages/SwapResult/style.ts
Labels: ⛲ Type: Feature/Function, 📑Type: Feature/Document, 🎨Type: style
